version: '3.8'

services:
  web:
    build: .
    container_name: api-spanglish-api
    # command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    command: tail -f /dev/null
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - .env:/usr/src/app/.env
    ports:
      - 8005:8000
    networks:
      - network-spanglish-api      
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - TESTING=0
      - DB_HOST=${DB_HOST}      
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    links:
      - 'mysql'
    depends_on:
      - mysql
  mysql:
    container_name: mysql-spanglish-api
    image: mysql:latest
    ports:
      - '3310:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    networks:
      network-spanglish-api:
        ipv4_address: ${DB_HOST}
  phpmyadmin:
    container_name: phpmyadmin-spanglish-api
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    networks:
      - network-spanglish-api
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql
  postgresql:
    container_name: postgresql-spanglish-api
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    networks:
      network-spanglish-api:
        ipv4_address: ${POSTGRES_HOST}
  pgadmin:
    container_name: pgadmin-spanglish-api
    image: dpage/pgadmin4:latest
    restart: always
    networks:
      - network-spanglish-api
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "postgresql:pgsql-server"      
volumes:
    mysql-data:
    db-data: {}
    pgadmin-data: {}    
networks:
    network-spanglish-api:
      ipam:
        driver: default
        config:
          - subnet: 171.28.0.0/16